baseURL = 'https://vipinvip.github.io/'
languageCode = 'en-us'
title = 'VIPIN K P'

homeSubtitle = "Something i wanna say"

theme        = "hello-friend-ng"

enableSharingButtons = true

[[menu.main]]
    identifier = "codes"
    name       = "Codes"
    url        = "/codes"
